### ISSUE TITLE
Create_raster don't work

### ISSUE THREAD

**Issue by fundor333** [wbierbower/fauxgeo#1]
I used your function create_raster in a QGIS plugin and I had this error

> AttributeError: 'NoneType' object has no attribute 'SetGeoTransform'

On the line with

> raster.SetGeoTransform((orgX, pixWidth, rotX, orgY, rotY, pixHeight))

**Comment by wbierbower** [comment]
Hi Fundor,  this library is still in the planning stage, but thanks for your interest.
